version: 2.6

executors: # Define an executor
  my-executor:
    docker:
      - image: cimg/base:2024.01
# Define the jobs we want to run for this project
jobs:
  build:
    executor: my-executor3
    steps:
      - checkout
      - run: echo "build"
  test:
    executor: my-executor3
    steps:
      - checkout
      - run: echo "test"

#THIS IS THE CHANGED YAML FILE FOR CHECKING THE PULL REQUEST GITHUB ACTION
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
