name: Changes in YAML

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/detectors/*.yaml" 
  workflow_dispatch:

jobs:
  pull_request_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Detect Modified File
        id: get-file
        run: |
          CHANGED_FILE=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^src/detectors/.*\.yaml$' || echo "")
          if [ -z "$CHANGED_FILE" ]; then
            echo "No YAML files detected. Exiting."
            exit 0
          fi
          echo "file=$CHANGED_FILE" >> $GITHUB_ENV


      - name: Output Changed File
        run: |
          echo "Detected YAML file: $file"
        env:
          file: ${{ env.file }}
